version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresql_container
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: Dev1234567
      POSTGRES_DB: dev
    ports:
      - "5435:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql
    networks:
      - postgres_network
    # init scryllaDB with auth
  crylladb:
    image: scylladb/scylla:latest
    container_name: scylladb_container
    restart: always
    environment:
      SCYLLA_CLUSTER_NAME: "dev_cluster"
      SCYLLA_AUTHENTICATION_ENABLED: "true"
      SCYLLA_USER: dev
      SCYLLA_PASSWORD: Dev1234567
    ports:
      - "9042:9042"
      - "9160:9160"
    networks:
      - crylladb_network

volumes:
  postgres_data:
    driver: local
  crylladb_data:
    driver: local

networks:
  postgres_network:
    driver: bridge
  crylladb_network:
    driver: bridge